version: "3.8"

services:
  redis:
    build: redis
    ports:
      - 6379:6379
  agent:
    build: .
    command:
      [
        "./sweep.sh",
        "--gpt=${GPT}",
      ]
    volumes:
      - "${PWD}/logs:/tmp/bsuite"
      - "${HOME}/.cache/GPT/:/root/.cache/GPT"
      - "${HOME}/.cache/huggingface/:/root/.cache/huggingface"
    deploy:
      replicas: ${REPLICAS}